# Generated by Django 3.1.3 on 2021-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_user'),
        ('tournaments', '0003_auto_20210417_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='teams.Team'),
        ),
    ]
