# Generated by Django 3.1.3 on 2021-04-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
    ]
