# Generated by Django 3.1.3 on 2021-04-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20210420_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arena',
            field=models.ForeignKey(blank=True, default='Arena 1', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.arena'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timesheet',
            field=models.ForeignKey(blank=True, default='7:00-8:00', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.timesheet'),
        ),
    ]
