# Generated by Django 3.1.3 on 2021-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20210421_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='arena',
            field=models.ManyToManyField(
                blank=True, default=None, to='bookings.Arena'),
        ),
        migrations.AddField(
            model_name='date',
            name='timesheet',
            field=models.ManyToManyField(
                blank=True, default=None, to='bookings.Timesheet'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
