# Generated by Django 3.1.3 on 2021-04-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20210421_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
    ]
