# Generated by Django 3.1.3 on 2021-04-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20210428_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arena',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timesheet',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.date'),
        ),
    ]
