# Generated by Django 3.1.3 on 2021-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20210428_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='dates',
            field=models.DateTimeField(),
        ),
    ]
