# Generated by Django 3.1.3 on 2021-05-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20210502_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='new_list',
        ),
    ]
